name: API Automation Tests

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Cache Maven dependencies
        uses: actions/cache@v3
        with:
          path: ~/.m2/repository
          key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
          restore-keys: ${{ runner.os }}-maven-

      - name: Build FastAPI Docker image
        run: docker build -t bookstore-api ./bookstore

      - name: Run FastAPI Docker container
        run: docker run -d -p 8000:8000 --name bookstore-api bookstore-api

      - name: Wait for FastAPI to be ready
        run: |
          echo "Waiting for API to be available..."
          sleep 10
          curl --retry 10 --retry-delay 3 --retry-connrefused http://localhost:8000/health

      - name: Run Rest Assured tests
        run: mvn clean test

      - name: Upload TestNG reports
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: test-reports
          path: target/surefire-reports
