name: API Automation Tests

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:
    inputs:
      environment:
        description: 'Target environment (dev, qa, stage, prod)'
        required: true
        default: 'dev'

jobs:
  test:
    runs-on: ubuntu-latest

    env:
      TARGET_ENV: ${{ github.event.inputs.environment || 'dev' }}
      JAVA_HOME_17_X64: /opt/hostedtoolcache/Java_Temurin-Hotspot_jdk/17.0.16-8/x64
      BASE_URL: https://your-api-url.com

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Java 17
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: Cache Maven packages
        uses: actions/cache@v4
        with:
          path: |
            ~/.m2/repository
            !~/.m2/repository/org/jacoco
          key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
          restore-keys: ${{ runner.os }}-maven

      - name: Install dependencies
        run: mvn clean install -DskipTests

      - name: Run Tests with Coverage and Allure Report
        run: mvn clean test verify -DsuiteXmlFile=testng.xml
        env:
          BASE_URL: ${{ env.BASE_URL }}

      - name: Generate JaCoCo Code Coverage Report
        run: mvn jacoco:report

      - name: Upload Allure Report
        uses: actions/upload-artifact@v4
        with:
          name: allure-report
          path: target/allure-report

      - name: Upload JaCoCo Code Coverage Report
        uses: actions/upload-artifact@v4
        with:
          name: jacoco-coverage-report
          path: target/site/jacoco
